# Sidebar navigation

- label: 'Architecture'
  items:
    - label: 'Observability'
      link: '/architecture/observability'
    - label: 'Performance'
      link: '/architecture/performance'
    - label: 'Resiliency'
      link: '/architecture/resiliency'
    - label: 'Scalability'
      link: '/architecture/scalability'
    - label: 'Security'
      link: '/architecture/security'
- label: 'Codez'
  items:
    - label: 'My Example'
      link: '/my-example'
